name: Release new Typebot version

on:
  pull_request:
    branches:
      - latest
  push:
    branches:
      - latest

jobs:
  build:
    strategy:
      matrix:
        app: ["builder", "viewer"]
        platform:
          - linux/amd64
          - linux/arm64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ahmedkhaled4d/zazubot-${{ matrix.app }}
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=ahmedkhaled4d/zazubot-${{ matrix.app }},push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            SCOPE=${{ matrix.app }}

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.app }}-${{ matrix.platform }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        app: ["builder", "viewer"]
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-${{ matrix.app }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create manifest list
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(printf 'ahmedkhaled4d/zazubot-${{ matrix.app }}@sha256:%s ' *) \
            -t ahmedkhaled4d/zazubot-${{ matrix.app }}:latest

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ahmedkhaled4d/zazubot-${{ matrix.app }}:latest
