name: Release new zazubot version

on:
  pull_request:
    branches:
      - latest
  push:
    branches:
      - latest

jobs:
  build-amd:
    env:
      DATABASE_URL: "postgresql://"
    strategy:
      matrix:
        app: ["builder", "viewer"]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract existing image metadata
        id: image-meta
        uses: docker/metadata-action@v4
        with:
          images: ahmedkhaled4d/zazubot-${{ matrix.app }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.image-meta.outputs.labels }}
          tags: ${{ steps.image-meta.outputs.tags }}
          platforms: linux/amd64
          cache-from: type=gha,scope=${{ matrix.app }}-amd
          cache-to: type=gha,scope=${{ matrix.app }}-amd,mode=max
          build-args: |
            SCOPE=${{ matrix.app }}

  build-arm:
    env:
      DATABASE_URL: "postgresql://"
    strategy:
      matrix:
        app: ["builder", "viewer"]
    runs-on: buildjet-8vcpu-ubuntu-2204-arm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Extract existing image metadata
        id: image-meta
        uses: docker/metadata-action@v4
        with:
          images: ahmedkhaled4d/zazubot-${{ matrix.app }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          labels: ${{ steps.image-meta.outputs.labels }}
          tags: ${{ steps.image-meta.outputs.tags }}
          platforms: linux/arm64
          cache-from: type=gha,scope=${{ matrix.app }}-arm
          cache-to: type=gha,scope=${{ matrix.app }}-arm,mode=max
          build-args: |
            SCOPE=${{ matrix.app }}

  # Existing merge-and-push and create-release jobs remain the same
